name: DevSecOps Pipeline for OWASP Juice Shop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Step 1: SAST (Static Application Security Testing) with CodeQL
  sast:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  # Step 2: SCA (Software Composition Analysis) with OWASP Dependency-Check
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Dependency-Check
        run: |
          # Download Dependency-Check (latest stable version: 7.4.0 as of 2024)
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v7.4.0/dependency-check-7.4.0-release.zip
          # Create a directory and extract Dependency-Check into it
          mkdir dependency-check
          unzip dependency-check-7.4.0-release.zip -d dependency-check

      - name: Run Dependency-Check
        run: |
          # Run the Dependency-Check scan with an output report in HTML format
          dependency-check/bin/dependency-check.sh --scan . --format HTML --out dependency-check-report.html

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report.html
