name: Deploy OWASP Juice Shop and Run OWASP ZAP DAST

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # DAST job for running OWASP ZAP against the Juice Shop app
  zap-dast:
    runs-on: ubuntu-latest

    services:
      # Start the Juice Shop application in a Docker container
      juice-shop:
        image: bkimminich/juice-shop:latest
        options: --publish 3000:3000

    steps:
      # Step 1: Wait for Juice Shop to be ready
      - name: Wait for Juice Shop to be ready
        run: |
          echo "Waiting for Juice Shop to be available..."
          until curl --silent --fail http://localhost:3000; do
            echo "Waiting for Juice Shop..."
            sleep 5
          done
          echo "Juice Shop is ready!"

      # Step 2: Set up OWASP ZAP and run DAST against the Juice Shop app
      - name: Set up ZAP
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:3000'

      # Step 3: Upload ZAP report as artifact
      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: /zap/wrk/*/zap-report.html
