name: Deploy OWASP Juice Shop and Run OWASP ZAP DAST

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # DAST job for running OWASP ZAP against the Juice Shop app
  zap-dast:
    runs-on: ubuntu-latest

    services:
      # Start the Juice Shop application in a Docker container
      juice-shop:
        image: bkimminich/juice-shop:latest
        options: --publish 3000:3000

    steps:
      # Step 1: Wait for Juice Shop to be ready
      - name: Wait for Juice Shop to be ready
        run: |
          echo "Waiting for Juice Shop to be available..."
          until curl --silent --fail http://localhost:3000; do
            echo "Waiting for Juice Shop..."
            sleep 5
          done
          echo "Juice Shop is ready!"

      # Step 2: Set up OWASP ZAP and run DAST against the Juice Shop app
      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:3000'
          format: 'html,json,md'  # Generate HTML, JSON, and Markdown reports
          report: 'zap_report.html'
          json_report: 'zap_report.json'
          md_report: 'zap_report.md'

      # Step 3: Upload ZAP reports as artifacts for download
      - name: Upload ZAP Reports as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: |
            zap_report.html
            zap_report.json
            zap_report.md
