name: CodeQL SAST and OWASP Dependency-Check SCA with DefectDojo

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # CodeQL SAST job for static code analysis
  codeql-sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Upload CodeQL Report to DefectDojo
        env:
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          ENGAGEMENT_ID: ${{ secrets.ENGAGEMENT_ID }}
        run: |
          if [ -f "results.sarif" ]; then
            curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
              -H "Authorization: Token $DEFECTDOJO_API_KEY" \
              -H "accept: application/json" \
              -F "scan_type=CodeQL" \
              -F "file=@results.sarif" \
              -F "engagement=$ENGAGEMENT_ID" \
              -F "auto_create_context=true" \
              -F "active=true" \
              -F "verified=false"
          else
            echo "CodeQL SARIF report not found."

  # OWASP Dependency-Check SCA job for dependency analysis
  owasp-dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        uses: dependency-check/github-action@v3
        with:
          format: "XML"
          output_directory: "./dependency-check-report"

      - name: Upload OWASP Dependency-Check Report to DefectDojo
        env:
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          ENGAGEMENT_ID: ${{ secrets.ENGAGEMENT_ID }}
        run: |
          REPORT_FILE="./dependency-check-report/dependency-check-report.xml"
          if [ -f "$REPORT_FILE" ]; then
            curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
              -H "Authorization: Token $DEFECTDOJO_API_KEY" \
              -H "accept: application/json" \
              -F "scan_type=Dependency Check" \
              -F "file=@$REPORT_FILE" \
              -F "engagement=$ENGAGEMENT_ID" \
              -F "auto_create_context=true" \
              -F "active=true" \
              -F "verified=false"
          else
            echo "OWASP Dependency-Check report not found."
