name: CodeQL SAST and OWASP Dependency-Check SCA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # CodeQL SAST job for static code analysis
  codeql-sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  # OWASP Dependency-Check SCA job for dependency analysis
  dependency-check-sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.5/dependency-check-7.0.5-release.zip
          unzip dependency-check.zip -d dependency-check
          sudo ln -s $(pwd)/dependency-check/bin/dependency-check.sh /usr/local/bin/dependency-check

      - name: Run OWASP Dependency-Check
        run: |
          dependency-check --project "Juice-Shop" \
                           --out dependency-check-report \
                           --scan $(pwd) \
                           --format "ALL"

      - name: Upload Dependency-Check Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Dependency-Check-Report
          path: dependency-check-report/      # Upload all report files from the output directory
