name: CodeQL SAST Analysis

# Trigger the workflow on pushes to the main or master branch, or on pull requests.
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  codeql-sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required for CodeQL to upload results to GitHub's security tab

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the code from your repo

      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'  # OWASP Juice Shop is primarily JavaScript-based

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

