name: CodeQL SAST and OWASP Dependency-Check SCA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # CodeQL SAST job for static code analysis
  codeql-sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  # OWASP Dependency-Check SCA job for dependency analysis
  dependency-check-sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OWASP Dependency-Check
        run: |
          # Download the latest Dependency-Check release
          curl -s https://api.github.com/repos/jeremylong/Dep
