name: SCA Scan with Snyk

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  snyk-sca-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Snyk
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Authenticate Snyk CLI
      - name: Authenticate Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      # Run Snyk test to check for vulnerabilities
      - name: Run Snyk Dependency Scan
        run: snyk test --all-projects

      # Optional: Monitor project in Snyk (keeps it up to date in Snyk dashboard)
      - name: Monitor Project on Snyk
        run: snyk monitor --all-projects
