name: CI Pipeline for OWASP Juice Shop - SCA with Snyk

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  actions: write

jobs:
  sca-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install -g snyk
          snyk auth "${SNYK_TOKEN}"

      - name: Run Snyk SCA Analysis
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --all-projects --severity-threshold=low

      - name: Generate Snyk HTML Report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --severity-threshold=low --json | snyk-to-html -o snyk_report.html

      - name: Upload SCA Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sca-report
          path: snyk_report.html
