name: SCA Scan for JSHOP-TEST

on:
  push:
    branches:
      - master  # Trigger when pushing to the master branch, or change to your main branch
  pull_request:
    branches:
      - master  # Trigger for pull requests targeting master branch

jobs:
  snyk-sca-scan:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Step 3: Authenticate with Snyk using the API token stored in GitHub secrets
      - name: Authenticate with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Make sure you have added your SNYK_TOKEN in GitHub secrets
        run: snyk auth $SNYK_TOKEN

      # Step 4: Run Snyk SCA test for the "JSHOP-TEST" project (based on the package.json)
      - name: Run Snyk SCA test for JSHOP-TEST
        run: snyk test --all-projects  # This will scan all projects within the repo (e.g., package.json, etc.)

      # Optional Step 5: Monitor the JSHOP-TEST project in Snyk for future vulnerability tracking
      - name: Monitor JSHOP-TEST with Snyk
        run: snyk monitor --all-projects
