name: SCA Scan for JSHO

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main  # Same as above, for PRs to the 'main' branch

jobs:
  snyk-sca-scan:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Step 3: Authenticate with Snyk using the API token stored in GitHub secrets
      - name: Authenticate with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      # Step 4: Run Snyk SCA test specifically for the JSHO project
      - name: Run Snyk SCA test for JSHO
        run: snyk test --project-name=JSHO

      # Optional Step 5: Monitor the JSHO project in Snyk (if you want to track issues over time)
      - name: Monitor with Snyk
        run: snyk monitor --project-name=JSHO
